routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/cart', 'CartController@index');

Route::resource('weight-log','WeightLogController');

app/Cart.php
<?php

namespace App;

class Cart
{
	private $products = [];

	function addProduct($productCode, $qty)
	{
		$key = array_search($productCode, array_column($this->products, 'product_code'));
		if(strlen($key)){
			$this->products[$key]['qty'] += $qty;
		}
		else{
			$this->products[] = ['product_code' => $productCode, 'qty' => $qty];
		}
	}

	function removeProduct($productCode)
	{
		foreach($this->products as $subKey => $subArray){
	          if($subArray['product_code'] == $productCode){
	               unset($this->products[$subKey]);
	          }
	     }
	}

	function showCart()
	{
		$result = "You can edit this in file :<br/>{ROOT}/app/Cart.php<br/>{ROOT}/app/Http/Controllers/CartController.php<br/>{ROOT}/routes/web.php<hr/>";
		foreach ($this->products as $key => $value) {
			$result .= $value['product_code']." (".$value['qty'].")<br/>";
		}
		return $result;
	}
}
?>

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/WeightLog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;

class WeightLog extends Model
{
    protected $fillable = [
        'log_date', 'max', 'min', 'variance'
    ];
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

class CartController extends Controller
{
    public function index()
    {
        $cart = new \App\Cart;
        $cart->addProduct("Topi Putih", 2);
        $cart->addProduct("Kemeja Hitam", 3);
        $cart->addProduct("Sepatu Merah", 1);
        $cart->addProduct("Sepatu Merah", 4);
        $cart->addProduct("Sepatu Merah", 2);
        $cart->removeProduct("Kemeja Hitam");
        $cart->removeProduct("Baju Hijau");
        return $cart->showCart();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/WeightLogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\WeightLogRepository;
use Validator;

class WeightLogController extends Controller
{
    /**
     * WeightLogController constructor.
     * @param WeightLogRepository $repo
     */
    public function __construct(WeightLogRepository $repo)
    {
        $this->repo = $repo;
    }

    public function index()
    {
    	$weight_logs = $this->repo->get();
    	$weight_stats = $this->repo->getStats();
        return view('weight_log.index',compact('weight_logs', 'weight_stats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('weight_log.create');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    	$validator = Validator::make($request->all(), [
            'log_date' => 'required|date',
	        'max' => 'required|numeric|min:'.$request->min,
	        'min' => 'required|numeric|max:'.$request->max
        ]);

        if ($validator->fails()) {
            return redirect()
            			->route('weight-log.create')
                        ->withErrors($validator)
                        ->withInput();
        }

        $request->request->add(['variance' => $request->max - $request->min]);
        
        $this->repo->create($request->all());
        return redirect()
        			->route('weight-log.index')
                	->with('success','WeightLog created successfully');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(int $id)
    {
        $weight_log = $this->repo->findById($id);
        return view('weight_log.show',compact('weight_log'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(int $id)
    {
        $weight_log = $this->repo->findById($id);
        return view('weight_log.edit',compact('weight_log'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, int $id)
    {
        $validator = Validator::make($request->all(), [
            'log_date' => 'required|date',
	        'max' => 'required|numeric|min:'.$request->min,
	        'min' => 'required|numeric|max:'.$request->max
        ]);

        if ($validator->fails()) {
            return redirect()
            			->route('weight-log.edit', $id)
                        ->withErrors($validator)
                        ->withInput();
        }

        $this->repo->update($request->all());
        return redirect()->route('weight-log.index')
                        ->with('success','WeightLog updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repo->delete($id);
        return redirect()->route('weight-log.index')
                        ->with('success','WeightLog deleted successfully');
    }
}

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sirclo</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	@yield('css-add')
</head>
<body>
 
<div class="container">
    @yield('content')
</div>
 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
@yield('js-add')

</body>
</html>

resources/views/weight_log/create.blade.php
@extends('layouts.default')
@section('css-add')
    <link href="https://cdn.jsdelivr.net/npm/gijgo@1.8.1/combined/css/gijgo.min.css" rel="stylesheet" type="text/css" />
@endsection
@section('js-add')
    <script src="https://cdn.jsdelivr.net/npm/gijgo@1.8.1/combined/js/gijgo.min.js" type="text/javascript"></script>
    <script>
        $('.datepicker').datepicker({
            uiLibrary: 'bootstrap4',
            format: 'yyyy-mm-dd'
        });
    </script>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <hr/>
            <div class="float-left">
                <h2>Add Berat</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-primary" href="{{ route('weight-log.index') }}">Back</a>
            </div>
        </div>
        <div class="col-md-12">
            <hr/>
            @if (count($errors) > 0)
                <div class="alert alert-danger" role="alert">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            {!! Form::open(array('route' => 'weight-log.store','method'=>'POST')) !!}
                <div class="form-group row">
                    <label for="log_date" class="col-sm-2 col-form-label">Tanggal</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control datepicker" id="log_date" name="log_date" placeholder="Click on calendar icon ->" readonly>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="min" class="col-sm-2 col-form-label">Min</label>
                    <div class="col-sm-4">
                        <input type="number" class="form-control" id="min" name="min" placeholder="Min weight">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="max" class="col-sm-2 col-form-label">Max</label>
                    <div class="col-sm-4">
                        <input type="number" class="form-control" id="max" name="max" placeholder="Max weight">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-success">Save</button>
                    </div>
                </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/weight_log/edit.blade.php
@extends('layouts.default')
@section('css-add')
    <link href="https://cdn.jsdelivr.net/npm/gijgo@1.8.1/combined/css/gijgo.min.css" rel="stylesheet" type="text/css" />
@endsection
@section('js-add')
    <script src="https://cdn.jsdelivr.net/npm/gijgo@1.8.1/combined/js/gijgo.min.js" type="text/javascript"></script>
    <script>
        $('.datepicker').datepicker({
            uiLibrary: 'bootstrap4',
            format: 'yyyy-mm-dd'
        });
    </script>
@endsection
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <hr/>
            <div class="float-left">
                <h2>Edit Berat</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-primary" href="{{ route('weight-log.index') }}">Back</a>
            </div>
        </div>
        <div class="col-lg-12">
            <hr/>
            @if (count($errors) > 0)
                <div class="alert alert-danger" role="alert">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            {{--  @php @dd($weight_log->id) @endphp  --}}
            {!! Form::model($weight_log,
                [
                    'method' => 'PATCH',
                    'route' => [
                        'weight-log.update', $weight_log->id
                    ]
                ])
            !!}
                <div class="form-group row">
                    <label for="log_date" class="col-sm-2 col-form-label">Tanggal</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control datepicker" id="log_date" name="log_date" placeholder="Click on calendar icon ->" readonly value="{{ $weight_log->log_date }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="min" class="col-sm-2 col-form-label">Min</label>
                    <div class="col-sm-4">
                        <input type="number" class="form-control" id="min" name="min" placeholder="Min weight" value="{{ $weight_log->min }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="max" class="col-sm-2 col-form-label">Max</label>
                    <div class="col-sm-4">
                        <input type="number" class="form-control" id="max" name="max" placeholder="Max weight" value="{{ $weight_log->max }}">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-success">Update</button>
                    </div>
                </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/weight_log/index.blade.php
@extends('layouts.default')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <hr/>
            <div class="float-left">
                <h2>Berat</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-primary" href="{{ route('weight-log.create') }}"> Add Weight Log</a>
            </div>
        </div>
        <div class="col-md-12">
            <hr/>
            @if ($message = Session::get('success'))
                <div class="alert alert-success" role="alert">
                  {{ $message }}
                </div>
            @endif
            <table class="table table-striped table-hover" width="100%">
                <thead class="thead-dark">
                    <th>Tanggal</th>
                    <th>Min</th>
                    <th>Max</th>
                    <th>Perbedaan</th>
                    <th width="30%">Action</th>
                </thead>
                @if(count($weight_logs) > 0)
                    @foreach ($weight_logs as $log)
                    <tr>
                        <td>{{ date('j F Y', strtotime($log->log_date)) }}</td>
                        <td>{{ number_format($log->min,2)+0 }}</td>
                        <td>{{ number_format($log->max,2)+0 }}</td>
                        <td>{{ number_format($log->variance,2)+0 }}</td>
                        <td>
                            <a class="btn btn-info" href="{{ route('weight-log.show',$log->id) }}">Show</a>
                            <a class="btn btn-primary" href="{{ route('weight-log.edit',$log->id) }}">Edit</a>
                            {!! Form::open(['method' => 'DELETE','route' => ['weight-log.destroy', $log->id],'style'=>'display:inline']) !!}
                            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                            {!! Form::close() !!}
                        </td>
                    </tr>
                    @endforeach
                    <tfoot class="table-primary">
                        <td>RATA - RATA</td>
                        <td>{{ number_format($weight_stats->min/$weight_stats->counted,2)+0 }}</td>
                        <td>{{ number_format($weight_stats->max/$weight_stats->counted,2)+0 }}</td>
                        <td>{{ number_format($weight_stats->variance/$weight_stats->counted,2)+0 }}</td>
                        <td>&nbsp;</td>
                    </tfoot>
                @else
                    <tr>
                        <td colspan="5">Data not found</td>
                    </tr>
                @endif
            </table>
        </div>
    </div>
@endsection

resources/views/weight_log/show.blade.php
@extends('layouts.default')
 
@section('content')
    <div class="row">
        <div class="col-md-12">
            <hr/>
            <div class="float-left">
                <h2>Show Berat</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-primary" href="{{ route('weight-log.index') }}">Back</a>
            </div>
        </div>
        <div class="col-md-12">
            <hr/>
            <table class="table table-bordered" width="100%">
                <tr>
                    <td width="15%">Tanggal</td>
                    <td>{{ $weight_log->log_date }}</td>
                </tr>
                <tr>
                    <td>Max</td>
                    <td>{{ $weight_log->max }}</td>
                </tr>
                <tr>
                    <td>Min</td>
                    <td>{{ $weight_log->min }}</td>
                </tr>
                <tr>
                    <td>Perbedaan</td>
                    <td>{{ $weight_log->variance }}</td>
                </tr>
            </table>
        </div>
    </div>
@endsection